--CREATE Employee Table
CREATE TABLE Employee
(
	ID INT NOT NULL IDENTITY (1000, 1) PRIMARY KEY,
	FirstName NVARCHAR(60) NULL,
	LastName NVARCHAR(30) NULL,
	SSN INT NULL,
	DeptID INT NULL
)
GO

ALTER TABLE Employee DROP COLUMN
	SSN;

ALTER TABLE Employee ADD
	SSN NVARCHAR(9);

--CREATE EmpDetails Table
GO
CREATE TABLE EmpDetails
(
	ID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	EmployeeID INT NOT NULL,
	Salary MONEY NULL,
	Address1 NVARCHAR(90) NULL,
	Address2 NVARCHAR(90) NULL,
	City NVARCHAR(30) NULL,
	State NVARCHAR(30) NULL,
	Country NVARCHAR(60) NULL
)
GO

--ADD FK to EMPLOYEE
ALTER TABLE EmpDetails ADD CONSTRAINT
FK_EmpDetails_Employee FOREIGN KEY (EmployeeID) REFERENCES Employee (ID)

GO
--CREATE Department Table
CREATE TABLE Department
(
	ID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	Name NVARCHAR(90) NULL,
	Location NVARCHAR(90) NULL
)
GO
--ADD FK to Employee
ALTER TABLE Employee ADD CONSTRAINT
FK_Employee_Department FOREIGN KEY (DeptID) REFERENCES Department (ID)